version: '3'
services:
  blog:
    image: guillermomaschwitz/blog:1
    container_name: blog
    volumes:
      - ./src:/home/node/blog
      - ./logs/node:/root/.npm/_logs
    working_dir: /home/node/blog
    environment: 
      - NODE_ENV=development
    networks:
      blog_net: {}
    ports:
      - ${WEB_PORT}:8000

networks:
  blog_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16
