version: '3'
services:
  blog:
    image: guillermomaschwitz/blog:1
    container_name: blog
    volumes:
      - ./blog:/home/node/blog
      - ./logs/node:/root/.npm/_logs
    working_dir: /home/node/blog
    environment: 
      - NODE_ENV=development
    networks:
      blog_net: {}
    expose: ["${WEB_PORT}"]
    ports:
      - "${WEB_PORT}:8000"
    command: "gatsby develop -H 0.0.0.0 --port ${WEB_PORT}"

networks:
  blog_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16
