version: '3'
services:
  blog:
    image: guillermomaschwitz/blog:${PROJECT_VERSION}-development
    container_name: blog
    volumes:
      - ./blog:/home/node/blog
      - ./logs/node:/root/.npm/_logs
    networks:
      net: {}
    expose: ["${WEB_PORT}"]
    ports:
      - "${WEB_PORT}:8000"

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16
