version: '3'
services:
  blog:
    image: guillermomaschwitz/blog:3-development
    container_name: blog
    volumes:
      - ./blog:/home/node/blog
    networks:
      net: {}
    ports:
      - ${PORT}:${PORT}
    environment:
      DEBUG: "gatsby:query-watcher"

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16
